### ISSUE TITLE
Page blank after Policyholder/Secretary selection 

### ISSUE THREAD

**Issue by cylon56** [LuisOsta/TandaPay#28]
During setup, after selecting either Policyholder or Secretary, pressing Next brings up a blank page.

**Comment by LuisOsta** [comment]
@cylon56 In future try to use one of the issue templates if possible. Can you post the console output during the error and what wallet provider you picked?

**Comment by cylon56** [comment]
![image](https://user-images.githubusercontent.com/18362080/60391575-33c8c880-9ab7-11e9-95b7-1046edc034e7.png)

**Comment by LuisOsta** [comment]
@cylon56 This seems to be an issue with web3 version, I think the incorrect version of web3 is being pushed to production.

**Comment by LuisOsta** [comment]
@cylon56 Were you using your phone or a computer? and what browser were you using?

**Comment by LuisOsta** [comment]
@cylon56 Can you check if you're still seeing those errors, should be fixed now

**Comment by cylon56** [comment]
Works now!
