### ISSUE TITLE
User Setting Not being Pulled From DB

### ISSUE THREAD

**Issue by LuisOsta** [LuisOsta/TandaPay#36]
**Describe the bug**
When you go to the user advanced settings. The notifications settings is empty apart from the table headers.
Error: Network Error
OPTIONS http://localhost:8080/user/settings net::ERR_CONNECTION_REFUSED

**To Reproduce**
1. Create a new user account
2. Click on user advanced settings
3. Notification settings should be empty
4. See an error in the console

**Expected behavior**
The full list of settings available to the user for email and SMS

 notifications should be able to be seen and changed.

**Screenshots**
![Error Message](https://user-images.githubusercontent.com/18711855/60857582-bc8ae700-a1d0-11e9-8eb6-890205ef28cd.PNG)

**Comment by wtfaremyinitials** [comment]
Issue caused by wrong url being used for the api. Here's the relevant TODO: https://github.com/LuisOsta/TandaPay/pull/32#discussion_r300148141. I know the correct URL now; I'll fix it later today.

**Comment by LuisOsta** [comment]
Localhost Issue fixed, but still not working. Now there's a network error

> xhr.js:166 Mixed Content: The page at 'https://peerless-dahlia-229121.appspot.com/admin/profile/advanced' was loaded over HTTPS, but requested an insecure XMLHttpRequest endpoint 'http://backend-api-dot-peerless-dahlia-229121.appspot.com/user/settings'. This request has been blocked; the content must be served over HTTPS.

**Comment by LuisOsta** [comment]
@wtfaremyinitials 
Cors Error;

> Access to XMLHttpRequest at 'https://backend-api-dot-peerless-dahlia-229121.appspot.com/user/settings' from origin 'https://peerless-dahlia-229121.appspot.com' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource.

**Comment by wtfaremyinitials** [comment]
@LuisOsta use the original URL https://backend-app-dot-peerless-dahlia-229121.appspot.com to access the app. Works there

**Comment by LuisOsta** [comment]
@wtfaremyinitials  Why is the application hosted on the API endpoint?

**Comment by wtfaremyinitials** [comment]
That’s the URL you gave me. I’ll add that other one if that’s the right one

**Comment by LuisOsta** [comment]
So have you been using that URL as the API endpoint? Or what exactly?

**Comment by wtfaremyinitials** [comment]
That URL is the only one I was aware of where the app backend is deployed

**Comment by LuisOsta** [comment]
@wtfaremyinitials Oh okay sorry about that I must have misspelled it. The application is deployed at: https://peerless-dahlia-229121.appspot.com/admin and the API is deployed at https://backend-api-dot-peerless-dahlia-229121.appspot.com/

For some reason, GCloud was allowing the application to be reached via https://backend-app-dot-peerless-dahlia-229121.appspot.com. That's an issue I'll have to look into

**Comment by LuisOsta** [comment]
Whitelist on API fixed works now.
