### ISSUE TITLE
Fortmatic Wallet Provider hangs on connect 

### ISSUE THREAD

**Issue by cylon56** [LuisOsta/TandaPay#59]
**Describe the bug**
When selecting Formatic as the wallet provider, the application hangs with a loading icon that never ends. This occured on the desktop after having connected Fortmatic successfully on mobile the day before using the same Google account.

**To Reproduce**
1. Go to 'https://peerless-dahlia-229121.appspot.com/setup' and login using Google
2. Select Secretary as your role
3. Click on 'Connect' under Formatic
4. Get a never-ending loading icon

**Expected behavior**
Expect to see a Fortmatic prompt where I enter my phone number

**Screenshots**
![image](https://user-images.githubusercontent.com/18362080/61246995-c8693280-a715-11e9-9afd-da90d60fa53c.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Chrome
 - Version 75.0.3770.100 (Official Build) (64-bit)

**Comment by LuisOsta** [comment]
Fixed in merge
