### ISSUE TITLE
Secretary Can't invite users via email

### ISSUE THREAD

**Issue by LuisOsta** [LuisOsta/TandaPay#69]
**Describe the bug**
Once a secretary has created a group, they aren't able to invite new members to join their group.
In the API logs the following error appears:
` UnhandledPromiseRejectionWarning: Error: username is required at new Twilio
`
**To Reproduce**
1. Login/Signup as a secretary
2. Create a group
3. Invite new member via form
4. See an error in API logs

**Expected behavior**
There should be a loading icon in the button while the invite is being sent and then the secretary should be routed to the group's page. The invited user should receive the invite email with the group's access code.

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] Windows 10
 - Browser [e.g. chrome, safari] Chrome
 - Version [e.g. 22] 75.0.3770.142 (Official Build) (64-bit)

**Comment by wtfaremyinitials** [comment]
This is a configuration issue. ` UnhandledPromiseRejectionWarning: Error: username is required at new Twilio` is the error that the Twilio nodejs library throws when the username passed to it. This is done here in the code: https://github.com/LuisOsta/TandaPay/blob/4780dbf/api/lib/twilio.js#L1-L20. Please ensure that there are valid credentials in those config properties.

**Comment by LuisOsta** [comment]
@wtfaremyinitials I have added the envs to the API so the issue is fixed.
