### ISSUE TITLE
Group Invitation Email links to incorrect app url

### ISSUE THREAD

**Issue by LuisOsta** [LuisOsta/TandaPay#70]
**Describe the bug**
The link to the application in the invitation email contains the wrong URL. Currently, it links to https://backend-app-dot-peerless-dahlia-229121.appspot.com/ and it should be linking to https://peerless-dahlia-229121.appspot.com/. Furthermore, currently, the "(Group Name)" text has the styling of a link but does not link to anything. It should either link to the application or have the styling of the regular text

**To Reproduce**
1. Log in as a secretary
2. Click on 'invite members' and invite a new member
3. Wait for the email provided in the invitation to receive the invitation
4. See the URL issue in '(group name)' and 'Accept Invitation".

**Expected behavior**
The links in the email invitation should link to https://peerless-dahlia-229121.appspot.com/

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] Windows 10
 - Browser [e.g. chrome, safari] Chrome
 - Version [e.g. 22] 75.0.3770.142 (Official Build) (64-bit)

**Comment by wtfaremyinitials** [comment]
The URL https://backend-app-dot-peerless-dahlia-229121.appspot.com/ was provided by @LuisOsta in this Discord message: https://discordapp.com/channels/577648686176141322/577648686176141325/594593004648398873. It's singular reference in the codebase is here: https://github.com/LuisOsta/TandaPay/blob/api-stable/api/controllers/group.js#L123. I will change it as soon as possible.

**Comment by LuisOsta** [comment]
@wtfaremyinitials Yes as we discussed on the scrum call last week I believe. I believe that's the last instance of the incorrect URL that needs to be updated, as the whitelist has already been changed.
