### ISSUE TITLE
User Joining Not Working

### ISSUE THREAD

**Issue by LuisOsta** [LuisOsta/TandaPay#71]
**Describe the bug**
When a secretary invites a new member into the group, the user can't join the appropriate group. Instead, they're asked to create a new group when they go to the 'groups page'.
The two main issues are:

1. There are no user role checks on the Groups page, no policyholder should ever see the groups creation page.
2. When a new user joins as a policyholder, they're not being added into the appropriate group they were invited to.

**To Reproduce**
1. Go to group page as a secretary
2. Invite a new member to the group
3. Check email provided by the secretary for the invitation email
4. Join as a policyholder with the given access code
5. See the group page has the group creation info and form
6. Check MongoDB users collection and see the groupID for the new user does not match the appropriate groupID
7. Check MongoDB groups collection and see the secretary's group's members list lacks the newly invited user.

**Expected behavior**
The user should be able to join the group they were invited to and see the groups dashboard after signing up on the 'groups page'.

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] Windows 10
 - Browser [e.g. chrome, safari] Chrome
 - Version [e.g. 22] 75.0.3770.142 (Official Build) (64-bit)

**Additional context**
This issue also appeared on the deployed version.

**Comment by wtfaremyinitials** [comment]
> Check MongoDB users collection and see the groupID for the new user does not match the appropriate groupID

What group ID is the user assigned? For reference, The group ID assignment happens here https://github.com/LuisOsta/TandaPay/blob/api-stable/api/controllers/user.js#L34-L40

**Comment by LuisOsta** [comment]
@wtfaremyinitials the groupID assigned to the new user didn't match any currently existing groups. It was a completely new one

**Comment by wtfaremyinitials** [comment]
> Upon further research, it seems that the groupID may be set properly(at least now it is).

Was it being set wrong recently? I have made no code changes in the last few days.

> new user still isn't being added to the member's array in the group's document

This is a bug that will be addressed soon.

> the new user still sees the group creation UI instead of the dashboard

This is particularly surprising. The group creation UI is only shown [when the redux store's `.groupID` property is null](https://github.com/LuisOsta/TandaPay/blob/app-stable/client/src/Dashboard/pages/Group/components/HOCs.js#L33-L35). Could this be because the redux store is not updated at the end of the signup flow?

**Comment by LuisOsta** [comment]
@wtfaremyinitials I meant in the sense that while originally I thought the groupID was not being set properly, it seems to be correct now.
I simply didn't want to rule out the case that there's some async function that's causing it to be set to default and then changed later. I doubt that's the case but I'm unsure.

**Comment by LuisOsta** [comment]
@wtfaremyinitials That may be true about the redux store but I don't know, I think you should definitely check the user role first as a basic check to prevent any weird issues like this.

**Comment by wtfaremyinitials** [comment]
> definitely check the user role first as a basic check to prevent any weird issues like this

This makes sense, although I’m not sure what could reasonably shown to a policyholder who does not have a group ID (and therefore has no group to be shown on the dashboard)

**Comment by LuisOsta** [comment]
Simply have an error page fallback that notifies them there's been an issue with their group and to contact the secretary

**Comment by wtfaremyinitials** [comment]
I've discovered that the root cause of this is the `user.groupID` redux property is not set in the process of user set up. This is unexpected as it is set properly in the backend. I'm somewhat unfamiliar with the setup code but I'll take a shot at fixing it.
